### PR TITLE
Update info.json - PoSciDonDAO

### PR DESCRIPTION
**Pull request by ayatta**

### CODE REVIEW

**Comment by gingerheart86** [comment]
@ayatta we should keep the old logo, unless you have a squared version of the new one. 
The logo must be squared-shaped to fit.

**Comment by ayatta** [comment]
@gingerheart86 We noticed on VitaDAO's dashboard that their logo doesn't seem to be a square. Could we do something similar so that we can use this second logo we provided?

**Comment by gingerheart86** [comment]
@ayatta I'll check it with our dev and come back to you asap

**Comment by gingerheart86** [comment]
@ayatta we can work it out! 
please introduce these changes to your PR:

"primaryColor":"#78dfec" -- this should correct the colour issue

and replace the field "logo" for:

"squareLogo": "https://i.imgur.com/JfhAvQW.jpg",
"displayName": "https://i.imgur.com/AQ6dvBc.png"

We should keep the squared logo for the small logo that appears in the list.

**Comment by gingerheart86** [comment]
@ayatta I'm trying to solve the error!

**Comment by ayatta** [comment]
Alright! Also I see that VitaDAO's rectangle logo is set using the "logo" key in the json file and their json file does not have the "squareLogo" or "displayName" keys. Maybe these json file keys are causing the build problem? Do we perhaps have to change the size of the logo so that it can fit the page?

**Comment by gingerheart86** [comment]
@ayatta I found out the mistake :)
Plz check it out.

**Comment by ayatta** [comment]
@gingerheart86 looks great!!! thank you!

**Pull request merged**
